// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ-ryK8EqTl7-toBxTK_WVFe1QZQXtNcg',
    appId: '1:452187876289:web:3114f680b9c2a8ebba9d40',
    messagingSenderId: '452187876289',
    projectId: 'evently-c16-sun',
    authDomain: 'evently-c16-sun.firebaseapp.com',
    storageBucket: 'evently-c16-sun.firebasestorage.app',
    measurementId: 'G-VCC06HHNCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD43wFw391OxGf9Q6kpBQt5K8oYMBDCOpg',
    appId: '1:452187876289:android:02d5e0230a174450ba9d40',
    messagingSenderId: '452187876289',
    projectId: 'evently-c16-sun',
    storageBucket: 'evently-c16-sun.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKObDgxY_w4PfA3v82VAezl5HO2Ost10U',
    appId: '1:452187876289:ios:3bdc3c352fbde32eba9d40',
    messagingSenderId: '452187876289',
    projectId: 'evently-c16-sun',
    storageBucket: 'evently-c16-sun.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC16Sun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKObDgxY_w4PfA3v82VAezl5HO2Ost10U',
    appId: '1:452187876289:ios:3bdc3c352fbde32eba9d40',
    messagingSenderId: '452187876289',
    projectId: 'evently-c16-sun',
    storageBucket: 'evently-c16-sun.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC16Sun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ-ryK8EqTl7-toBxTK_WVFe1QZQXtNcg',
    appId: '1:452187876289:web:6858470ce5ab7199ba9d40',
    messagingSenderId: '452187876289',
    projectId: 'evently-c16-sun',
    authDomain: 'evently-c16-sun.firebaseapp.com',
    storageBucket: 'evently-c16-sun.firebasestorage.app',
    measurementId: 'G-98MF4TSNST',
  );
}
